### ISSUE TITLE
logout problem ...slow

### ISSUE THREAD

**Issue by amervelic** [JustHTTP/Just#81] opened 2017-06-11 18:27 UTC
func logout (completion:@escaping (Any)->()) {
    
        let urlString = "https://bhmobile.bhtelecom.ba/c/portal/logout"
        
        Just.get(urlString, allowRedirects:false) { r  in
            
            DispatchQueue.main.async(execute: {
                    completion(r.description)
            })
        }

Same logout on android (OkHttp library 80ms - 200ms status code 302)
On iOS - 1s (3G) - 5s (Edge) status code 200 but i need status 302
Why ?

**Comment by dduan** [comment] 2018-09-27 17:32
I doubt this is caused by `Just`. Closing for now. Feel free to re-open if you still have questions.

**Closed by dduan** 2018-09-27 17:32 UTC
